// pc-admin-react/src/pages/management/user/profile/index.tsx
import { Col, Row } from "antd";
import BasicInfoCard from "./basic-info-card";
import SecuritySettingsCard from "./security-settings-card";

export default function UserProfilePage() {
	return (
		<div className="p-4">
			<Row gutter={[16, 16]} align="stretch" wrap>
				<Col xs={24} sm={24} md={10} lg={10} xl={7} xxl={7}>
					<BasicInfoCard />
				</Col>
				<Col xs={24} sm={24} md={14} lg={14} xl={17} xxl={17}>
					<SecuritySettingsCard />
				</Col>
			</Row>
		</div>
	);
}

// pc-admin-vue3/src/views/user/profile/index.vue
<template>
  <div class="gi_page">
    <a-row wrap :gutter="[16, 16]" align="stretch">
      <a-col :xs="24" :sm="24" :md="10" :lg="10" :xl="7" :xxl="7">
        <LeftBox />
      </a-col>
      <a-col :xs="24" :sm="24" :md="14" :lg="14" :xl="17" :xxl="17">
        <div>
          <PasswordPolicy />
        </div>
      </a-col>
    </a-row>
  </div>
</template>

<script setup lang="ts">
import LeftBox from './BasicInfo.vue'
import PasswordPolicy from './Security.vue'

defineOptions({ name: 'UserProfile' })
</script>

<style scoped lang="scss">
.gi_page {
  background-color: var(--color-bg-1);
}
</style>
